# Generated by Django 4.1.3 on 2022-11-14 13:34

from django.db import migrations, models
import stud_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[stud_app.validators.gmail_validation])),
                ('age', models.IntegerField(null=True)),
                ('Class', models.CharField(choices=[('a', '1st std'), ('b', '2nd std'), ('c', '3rd std'), ('d', '4th std'), ('e', '5th std'), ('f', '6th std'), ('g', '7th std'), ('h', '8th std'), ('i', '9th std'), ('j', '10th std'), ('k', '11th std'), ('l', '12th std')], default='1', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
